name: Release Docker Image
on: push

env:
  ORG: ashtacore
  PG_VER: 14
  TS_VERSION: 2.8.1
  PLATFORM: linux/arm/v7

jobs:

  # Build multi-arch TimescaleDB images for both TSL and OSS code.
  timescaledb:

    name: PG14-armv7
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      with:
        platforms: all

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Available platforms
      run: echo ${{ steps.buildx.outputs.platforms }}

    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USER }} --password-stdin

    - name: Build and push multi-platform Docker image for TimescaleDB
      run: make multi ORG=$ORG PG_VER=pg${PG_VER} TS_VERSION="${TS_VERSION}" PLATFORM=${PLATFORM}